name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production-env

    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        run: npm install && npm run build

      - name: Deploy to Production Server
        run: echo "Deploying to Production Environment...(/)"
